name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  awesome_dialog: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.0.0
  android_intent_plus: ^5.0.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
